### ISSUE TITLE
<async-fragment-error> is not rendered in case of exception

### ISSUE THREAD

**Issue by SunnyGurnani** [marko-js/marko-async#15] opened 2015-10-09 22:46 UTC
When I pass callback(err, null) in the renderer async-fragment-error is not rendered.

**Comment by patrick-steele-idem** [comment] 2015-10-09 23:18
For uncaught exceptions that is the expected behavior. There are no `try...catch` calls in the marko runtime and for async things they wouldn't help. If the job of the user data provider function to catch any errors. However, if you want exceptions to be caught then I suggest using promises instead of Node.js-style callbacks. This is because Promise implementations do use `try...catch` blocks during every step of the async promise chain.

**Comment by patrick-steele-idem** [comment] 2015-10-15 16:25
Hey @SunnyGurnani, did that answer your question? If not, please provide more details or share code to make the problem more clear. In the mean time I'll be adding more test cases around error handling.

I'm going to close this issue for now, but please feel to reopen if you are not satisfied with the answer. Thanks!

**Closed by patrick-steele-idem** 2015-10-15 16:25 UTC
