### ISSUE TITLE
Is it possible to change HTTP response code in Progressive rendering?

### ISSUE THREAD

**Issue by SunnyGurnani** [marko-js/marko-async#17] opened 2015-10-12 17:57 UTC
When using progressive rendering we make a call to service in `<async-renderer>` and the dataprovider method called by `<async-renderer>` dosent have access to HTTP request and response object.

In this case how can we set HTTP response code if service fails?

**Comment by patrick-steele-idem** [comment] 2015-10-15 16:22
Hey @SunnyGurnani, you wouldn't be able to change the HTTP response code after the first byte has been committed. When the first byte is committed to the HTTP response the HTTP response headers are committed. If a particular part of the page fails then it is best to flush an error message for that async fragment. If the problem is severe enough you can do one of the following:

- Show a modal to force the user to reload the page (and hope the problem is resolved for the next request)
- Flush a `<script>` block that redirects to an error page using client-side JavaScript

Error handling with progressive HTML rendering is a little tricker, so it is definitely a tradeoff. While buffering everything let's you do better server-side error handling it will perform much worse for pages that make async calls. It's usually better to optimize for the success case even if the error handling for the failure case is a little more complicated.

I'm going to go ahead and close this issue, but feel free to add more comments here if you would like to discuss further.

**Closed by patrick-steele-idem** 2015-10-15 16:22 UTC
